language: node_js
node_js:
  - '12'
services:
  - docker

notifications:
  email: false
  slack:
    rooms:
      secure: hzKQlSzA2buvf8IJCHgvWE4KL+sE2PZcw+CWfyeTEUfbforB89DN4ArFkhXSwD6/VdIqlJC/gKw36Yc+ujwq/2y+w3eWq0rLqizaO1uATwtAeZrYO/1GAAmG8AKb8xmkLinmdgjBrpV8IPNMcxY7bWvRBFsuSSNIlWK4X8CT53tXNpVuGYxEQCWJhvOjTcNF11Tzm/kZueb8okM3C7sDRVpoxSZSXz0+pIVg4DITWa6bX99I6XL26HEvBU21jUfZmR3Rcldqexygbi4VesBo7coaYW+U2RaDWbEg8/avKd/E1WuFy/YfVK9fNkBo5P0L5CZx0HKMHPpyWYBC7i6pI8sXHNZZ/U+KsvFwXr8ErA2fGOHiCgaH1tn90jIxIHtUSiNLGVCcG4TJDT5e5nkh1FbXii5GuzWRF5ZjBe169+2/trTU7DGeDcEZcjBqm9F5Vt5lUGY+PUTZ0czYvsw/n4Xj/gWnnmBOm1HC2XmZlr6bxxEgmGfSqFgqhLxuMibA5SsD2fJEcj7DcUpspygYtchmoKMRSin/R10/5pd7pPrS+0QlFdsVfy9Gt/BpSXQds31JywS8pxhPSpzuzGtcv0qoVuJa99qLVLGAYeiR6wHWY94+kCKQIC5MtP35Hp6RJYmanRn+vOqPF5GUelkGo5goHOYxw9PGZymz0zhmklg=
    on_success: always
    on_failure: always  

script:
  - |
   IMAGE_NAME="$TRAVIS_REPO_SLUG"
   if [[ -z "$TRAVIS_TAG" ]]; then
     IMAGE_TAG=latest
     KRAWLER_TAG=latest
   else
     IMAGE_TAG=$(node -p -e "require('./package.json').version")
     KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
   fi
   docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile -t $IMAGE_NAME:$IMAGE_TAG .

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true